import { describe, expect, it } from 'vitest';
import { z } from 'zod';
import reference from '../../test/php-reference/round-cases.json';
import { gameOddsHundredths, standingsOddsTenThousandths } from './crowd-ratio';
import { phpRound } from './php-round';

// Generated by PHP 8.4 itself: test/php-reference/round-cases.php.
const table = z
  .object({
    php: z.string(),
    round: z.array(
      z.object({ value: z.number(), places: z.int(), result: z.number() }),
    ),
    odds: z.array(
      z.object({
        total: z.int(),
        count: z.number(),
        game: z.number(),
        standings: z.number(),
      }),
    ),
  })
  .parse(reference);

describe('the PHP reference table', () => {
  it('was generated by PHP 8.4', () => {
    expect(table.php).toMatch(/^8\.4\./);
  });

  it('covers the half-way cases and every crowd of up to 100 voters', () => {
    expect(table.round.length).toBeGreaterThan(10_000);
    expect(table.odds).toHaveLength(100 + (100 * 101) / 2);
  });
});

describe('phpRound', () => {
  // A binary double sits just below these decimals; PHP rounds the decimal.
  it('rounds 1.005 to 1.01 and 0.285 to 0.29, as PHP does', () => {
    expect(phpRound(1.005, 2)).toBe(1.01);
    expect(Math.round(1.005 * 100) / 100).toBe(1);
    expect(phpRound(0.285, 2)).toBe(0.29);
    expect(Math.round(0.285 * 100) / 100).toBe(0.28);
  });

  it('agrees with PHP 8.4 on every reference case', () => {
    const disagreements = table.round.filter(
      ({ value, places, result }) =>
        !Object.is(phpRound(value, places), result),
    );
    expect(disagreements).toEqual([]);
  });

  it.each([
    ['a fractional place count', 1, 1.5],
    ['a negative place count', 1, -1],
    ['infinity', Number.POSITIVE_INFINITY, 2],
    ['not a number', Number.NaN, 2],
  ])('throws on %s', (_, value, places) => {
    expect(() => phpRound(value, places)).toThrow(/phpRound/);
  });
});

describe('crowd odds rounding', () => {
  it('odds: log2(3/2) is stored as 0.59, not 0.58', () => {
    expect(gameOddsHundredths(3, 2)).toBe(59);
    // Rounding once, straight to two places, gives the wrong 0.58.
    expect(Math.round(Math.log2(3 / 2) * 100)).toBe(58);
  });

  it('agrees with PHP 8.4 on every crowd of up to 100 voters', () => {
    const disagreements = table.odds.filter(
      ({ total, count, game, standings }) =>
        gameOddsHundredths(total, count) / 100 !== game ||
        standingsOddsTenThousandths(total, count) / 10_000 !== standings,
    );
    expect(disagreements).toEqual([]);
  });
});
